apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-worker-deployment
  labels:
    app: medscope-ocr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medscope-ocr
  template:
    metadata:
      labels:
        app: medscope-ocr
    spec:
      containers:
        - name: ocr-worker
          image: your-dockerhub-user/medscope-ocr:latest
          args: ["ocr.py", "/data/input.png"]
          volumeMounts:
            - name: input-volume
              mountPath: /data
      volumes:
        - name: input-volume
          emptyDir: {}